Pipeline:
  name: templates_global_demo

GitRepo:
  name: tsuyoGitRepoRes
  gitProvider: tsuyo_github
  path: tsuyo/jfrog-pipelines-demo
  branches:
    include: 'main'
    # exclude: 'main'

artifactoryIntegration: artifactory

Image:
  name: helloImageRes
  sourceRepository: docker
  # autoPull: false

DockerBuild:
  name: helloDockerBuildStep
  dockerImageName: kirasoa-docker.jfrog.io/hello
  dockerFileName: Dockerfile
  dockerFileLocation: 'templates/global'
  dockerImageTag: ${run_number}

DockerPush:
  name: helloDockerPushStep
  targetRepository: docker

BuildInfo:
  name: helloBuildInfoRes
  autoPublishBuildInfo: true
  # TODO: build number
