resources:
  - name: {{ .Values.gitRepo.name }}
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.gitRepo.provider }}
      path: {{ .Values.gitRepo.path }}
      # branches:
      #   include: master

  - name: {{ .Values.pipelines.name }}
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}

pipelines:
  - name: {{ .Values.pipelines.name }}
    steps:
      - name: npm_build
        type: NpmBuild
        configuration:
          resolverRepo: {{ .Values.artifactoryRepo.resolver.name }}
          sourceLocation: .
          integrations:
            - name:  {{ .Values.artifactory }}
          inputResources:
            - name: {{ .Values.gitRepo.name }}
        execution:
          # this is a workaround to change artifact name every time
          # if the same artifact name is used and it's used in reelase bundle,
          # you can't delete that file (can't override it) and a step might fail
          onStart:
            - pushd ${res_{{ .Values.gitRepo.name }}_resourcePath}
            - echo $(jq ".version=\"0.0.${run_number}\"" package.json) > package.json
            - popd

      - name: npm_publish
        type: NpmPublish
        configuration:
          repositoryName: {{ .Values.artifactoryRepo.target.name }}
          autoPublishBuildInfo: true
          integrations:
            - name: {{ .Values.artifactory }}
          inputSteps:
            - name: npm_build
          outputResources:
            - name: {{ .Values.pipelines.name }}